### ISSUE TITLE
Instructor dashboard filter enhancements

### ISSUE THREAD

**Issue by bmtcril** [openedx/platform-plugin-aspects#19]
Right now there are a few issues with the Instructor dashboard implementation in the LMS:

- It does not have the correct dashboard ID for the new course dashboard, instead the initial tab points to the old instructor dashboard
- It does not support localized dashboards, we need to add configuration and code to display the correctly localized dashboard for users
- We should change the top level tab from "Aspects" to "Analytics"
```[tasklist]
### Tasks
- [x] Use new Instructor Dashboard
- [x] Localized dashboards
- [x] Rename tab from Aspects to Analytics
```

**Comment by Ian2012** [comment]
Current work is here: https://github.com/openedx/platform-plugin-aspects/pull/24
